---
kind: pipeline
type: docker
name: CI/CD

base-job-config: &base-job-config
  image: docker:19.03.5
  privileged: true
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  volumes:
    - name: dockersock
      path: /var/run/docker.sock
  

steps:
- name: build and push DEV image
  <<: *base-job-config
  when:
    branch:
      - dev
  environment:
    TAG: dev
  commands:
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin dregistry.wallbtc.com
    - docker build --build-arg NODE_ENV=dev -t dregistry.wallbtc.com/bitteam/token.bit.team:$TAG .
    - docker push dregistry.wallbtc.com/bitteam/token.bit.team:$TAG

- name: performing DEVELOPE server update
  image: appleboy/drone-ssh:1.5.5
  when:
    branch:
      - dev
  settings:
    host: 192.168.74.9
    port: 22
    username: deploy
    key:
      from_secret: deploy_ssh_key
    script:
      - cd /var/www/html/token.bit.team
      - docker-compose pull
      - docker-compose up -d

steps:
- name: build and push PROD image
  <<: *base-job-config
  when:
    branch:
      - master
  environment:
    TAG: master
  commands:
    - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin dregistry.wallbtc.com
    - docker build --build-arg NODE_ENV=dev -t dregistry.wallbtc.com/bitteam/token.bit.team:$TAG .
    - docker push dregistry.wallbtc.com/bitteam/token.bit.team:$TAG

- name: performing PRODUCTION server update
  image: appleboy/drone-ssh:1.5.5
  when:
    branch:
      - master
  settings:
    host: 192.168.74.23
    port: 22
    username: deploy
    key:
      from_secret: deploy_ssh_key
    script:
      - cd token.bit.team
      - docker-compose pull
      - docker-compose up -d

- name: performing PRODUCTION server2 update
  image: appleboy/drone-ssh:1.5.5
  when:
    branch:
      - master
  settings:
    host: 192.168.74.27
    port: 22
    username: deploy
    key:
      from_secret: deploy_ssh_key
    script:
      - cd token.bit.team
      - docker-compose pull
      - docker-compose up -d

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
